version: '3.2'

services:
    api:
        image: ghcr.io/wenogk/mypiston
        container_name: piston_api
        restart: always
        privileged: true
        ports:
            - 2000:2000
        volumes:
            - ./data/piston/packages:/piston/packages
        tmpfs:
            - /tmp:exec
        environment:
            - PISTON_RUN_CPU_TIME=20000  # Set CPU time to 20 seconds
            - PISTON_RUN_TIMEOUT=15000